// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: NetConfig.proto
#ifndef GRPC_NetConfig_2eproto__INCLUDED
#define GRPC_NetConfig_2eproto__INCLUDED

#include "NetConfig.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace InforGuard_ {

class NetConfig final {
 public:
  static constexpr char const* service_full_name() {
    return "InforGuard_.NetConfig";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Load(::grpc::ClientContext* context, const ::InforGuard_::LoadReq& request, ::InforGuard_::LoadRes* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::LoadRes>> AsyncLoad(::grpc::ClientContext* context, const ::InforGuard_::LoadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::LoadRes>>(AsyncLoadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::LoadRes>> PrepareAsyncLoad(::grpc::ClientContext* context, const ::InforGuard_::LoadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::LoadRes>>(PrepareAsyncLoadRaw(context, request, cq));
    }
    virtual ::grpc::Status Save(::grpc::ClientContext* context, const ::InforGuard_::SaveReq& request, ::InforGuard_::SaveRes* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::SaveRes>> AsyncSave(::grpc::ClientContext* context, const ::InforGuard_::SaveReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::SaveRes>>(AsyncSaveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::SaveRes>> PrepareAsyncSave(::grpc::ClientContext* context, const ::InforGuard_::SaveReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::SaveRes>>(PrepareAsyncSaveRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Load(::grpc::ClientContext* context, const ::InforGuard_::LoadReq* request, ::InforGuard_::LoadRes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Load(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::LoadRes* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Load(::grpc::ClientContext* context, const ::InforGuard_::LoadReq* request, ::InforGuard_::LoadRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Load(::grpc::ClientContext* context, const ::InforGuard_::LoadReq* request, ::InforGuard_::LoadRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Load(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::LoadRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Load(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::LoadRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void Save(::grpc::ClientContext* context, const ::InforGuard_::SaveReq* request, ::InforGuard_::SaveRes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Save(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::SaveRes* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Save(::grpc::ClientContext* context, const ::InforGuard_::SaveReq* request, ::InforGuard_::SaveRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Save(::grpc::ClientContext* context, const ::InforGuard_::SaveReq* request, ::InforGuard_::SaveRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Save(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::SaveRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Save(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::SaveRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::LoadRes>* AsyncLoadRaw(::grpc::ClientContext* context, const ::InforGuard_::LoadReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::LoadRes>* PrepareAsyncLoadRaw(::grpc::ClientContext* context, const ::InforGuard_::LoadReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::SaveRes>* AsyncSaveRaw(::grpc::ClientContext* context, const ::InforGuard_::SaveReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::SaveRes>* PrepareAsyncSaveRaw(::grpc::ClientContext* context, const ::InforGuard_::SaveReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Load(::grpc::ClientContext* context, const ::InforGuard_::LoadReq& request, ::InforGuard_::LoadRes* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::LoadRes>> AsyncLoad(::grpc::ClientContext* context, const ::InforGuard_::LoadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::LoadRes>>(AsyncLoadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::LoadRes>> PrepareAsyncLoad(::grpc::ClientContext* context, const ::InforGuard_::LoadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::LoadRes>>(PrepareAsyncLoadRaw(context, request, cq));
    }
    ::grpc::Status Save(::grpc::ClientContext* context, const ::InforGuard_::SaveReq& request, ::InforGuard_::SaveRes* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::SaveRes>> AsyncSave(::grpc::ClientContext* context, const ::InforGuard_::SaveReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::SaveRes>>(AsyncSaveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::SaveRes>> PrepareAsyncSave(::grpc::ClientContext* context, const ::InforGuard_::SaveReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::SaveRes>>(PrepareAsyncSaveRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Load(::grpc::ClientContext* context, const ::InforGuard_::LoadReq* request, ::InforGuard_::LoadRes* response, std::function<void(::grpc::Status)>) override;
      void Load(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::LoadRes* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Load(::grpc::ClientContext* context, const ::InforGuard_::LoadReq* request, ::InforGuard_::LoadRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Load(::grpc::ClientContext* context, const ::InforGuard_::LoadReq* request, ::InforGuard_::LoadRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Load(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::LoadRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Load(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::LoadRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Save(::grpc::ClientContext* context, const ::InforGuard_::SaveReq* request, ::InforGuard_::SaveRes* response, std::function<void(::grpc::Status)>) override;
      void Save(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::SaveRes* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Save(::grpc::ClientContext* context, const ::InforGuard_::SaveReq* request, ::InforGuard_::SaveRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Save(::grpc::ClientContext* context, const ::InforGuard_::SaveReq* request, ::InforGuard_::SaveRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Save(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::SaveRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Save(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::SaveRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::InforGuard_::LoadRes>* AsyncLoadRaw(::grpc::ClientContext* context, const ::InforGuard_::LoadReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InforGuard_::LoadRes>* PrepareAsyncLoadRaw(::grpc::ClientContext* context, const ::InforGuard_::LoadReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InforGuard_::SaveRes>* AsyncSaveRaw(::grpc::ClientContext* context, const ::InforGuard_::SaveReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InforGuard_::SaveRes>* PrepareAsyncSaveRaw(::grpc::ClientContext* context, const ::InforGuard_::SaveReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Load_;
    const ::grpc::internal::RpcMethod rpcmethod_Save_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Load(::grpc::ServerContext* context, const ::InforGuard_::LoadReq* request, ::InforGuard_::LoadRes* response);
    virtual ::grpc::Status Save(::grpc::ServerContext* context, const ::InforGuard_::SaveReq* request, ::InforGuard_::SaveRes* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Load : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Load() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Load() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Load(::grpc::ServerContext* /*context*/, const ::InforGuard_::LoadReq* /*request*/, ::InforGuard_::LoadRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLoad(::grpc::ServerContext* context, ::InforGuard_::LoadReq* request, ::grpc::ServerAsyncResponseWriter< ::InforGuard_::LoadRes>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Save : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Save() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Save() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Save(::grpc::ServerContext* /*context*/, const ::InforGuard_::SaveReq* /*request*/, ::InforGuard_::SaveRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSave(::grpc::ServerContext* context, ::InforGuard_::SaveReq* request, ::grpc::ServerAsyncResponseWriter< ::InforGuard_::SaveRes>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Load<WithAsyncMethod_Save<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Load : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Load() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::InforGuard_::LoadReq, ::InforGuard_::LoadRes>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::InforGuard_::LoadReq* request, ::InforGuard_::LoadRes* response) { return this->Load(context, request, response); }));}
    void SetMessageAllocatorFor_Load(
        ::grpc::experimental::MessageAllocator< ::InforGuard_::LoadReq, ::InforGuard_::LoadRes>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::InforGuard_::LoadReq, ::InforGuard_::LoadRes>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Load() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Load(::grpc::ServerContext* /*context*/, const ::InforGuard_::LoadReq* /*request*/, ::InforGuard_::LoadRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Load(
      ::grpc::CallbackServerContext* /*context*/, const ::InforGuard_::LoadReq* /*request*/, ::InforGuard_::LoadRes* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Load(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::InforGuard_::LoadReq* /*request*/, ::InforGuard_::LoadRes* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Save : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Save() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::InforGuard_::SaveReq, ::InforGuard_::SaveRes>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::InforGuard_::SaveReq* request, ::InforGuard_::SaveRes* response) { return this->Save(context, request, response); }));}
    void SetMessageAllocatorFor_Save(
        ::grpc::experimental::MessageAllocator< ::InforGuard_::SaveReq, ::InforGuard_::SaveRes>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::InforGuard_::SaveReq, ::InforGuard_::SaveRes>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Save() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Save(::grpc::ServerContext* /*context*/, const ::InforGuard_::SaveReq* /*request*/, ::InforGuard_::SaveRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Save(
      ::grpc::CallbackServerContext* /*context*/, const ::InforGuard_::SaveReq* /*request*/, ::InforGuard_::SaveRes* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Save(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::InforGuard_::SaveReq* /*request*/, ::InforGuard_::SaveRes* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Load<ExperimentalWithCallbackMethod_Save<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Load<ExperimentalWithCallbackMethod_Save<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Load : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Load() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Load() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Load(::grpc::ServerContext* /*context*/, const ::InforGuard_::LoadReq* /*request*/, ::InforGuard_::LoadRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Save : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Save() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Save() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Save(::grpc::ServerContext* /*context*/, const ::InforGuard_::SaveReq* /*request*/, ::InforGuard_::SaveRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Load : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Load() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Load() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Load(::grpc::ServerContext* /*context*/, const ::InforGuard_::LoadReq* /*request*/, ::InforGuard_::LoadRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLoad(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Save : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Save() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Save() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Save(::grpc::ServerContext* /*context*/, const ::InforGuard_::SaveReq* /*request*/, ::InforGuard_::SaveRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSave(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Load : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Load() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Load(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Load() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Load(::grpc::ServerContext* /*context*/, const ::InforGuard_::LoadReq* /*request*/, ::InforGuard_::LoadRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Load(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Load(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Save : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Save() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Save(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Save() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Save(::grpc::ServerContext* /*context*/, const ::InforGuard_::SaveReq* /*request*/, ::InforGuard_::SaveRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Save(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Save(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Load : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Load() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InforGuard_::LoadReq, ::InforGuard_::LoadRes>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::InforGuard_::LoadReq, ::InforGuard_::LoadRes>* streamer) {
                       return this->StreamedLoad(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Load() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Load(::grpc::ServerContext* /*context*/, const ::InforGuard_::LoadReq* /*request*/, ::InforGuard_::LoadRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLoad(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InforGuard_::LoadReq,::InforGuard_::LoadRes>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Save : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Save() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InforGuard_::SaveReq, ::InforGuard_::SaveRes>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::InforGuard_::SaveReq, ::InforGuard_::SaveRes>* streamer) {
                       return this->StreamedSave(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Save() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Save(::grpc::ServerContext* /*context*/, const ::InforGuard_::SaveReq* /*request*/, ::InforGuard_::SaveRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSave(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InforGuard_::SaveReq,::InforGuard_::SaveRes>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Load<WithStreamedUnaryMethod_Save<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Load<WithStreamedUnaryMethod_Save<Service > > StreamedService;
};

}  // namespace InforGuard_


#endif  // GRPC_NetConfig_2eproto__INCLUDED
