// NetConfig.idl

#include "Exception.idl"

module InforGuard
{
	interface NetConfig
	{
		//获取远程配置内容
		long Load( in HostChain seqIpPort, in string cfgFileName, out string cfgFileContent )
			raises( ExceptionError );
		//保存远程配置文件
		long Save( in HostChain seqIpPort, in string cfgFileName, in string cfgFileContent )
			raises( ExceptionError );
	};
};
