// NetDirectory.idl

#include "Exception.idl"

module InforGuard
{
	interface NetDirectory
	{
		void Check() raises( ExceptionError );

		long GetTree(
			inout netCallData callData, 
			in HostChain seqIpPort,
			in string remotefoldername,
			in long mode,
			out NetFileTreeNode treenode
			) raises( ExceptionError );

		long GetList(
			inout netCallData callData, 
			in HostChain seqIpPort,
			in string remotefoldername,
			in long mode,
			out NetFileList filelist
			) raises( ExceptionError );

		long GetTreeEx(
			in HostChain seqIpPort,
			in string remotefoldername,
			in long mode,
			out NetFileTreeNode treenode
			) raises( ExceptionError );

		long GetListEx(
			in HostChain seqIpPort,
			in string remotefoldername,
			in long mode,
			out NetFileList filelist
			) raises( ExceptionError );
	};
};
