// NetWaterMark.idl

#include "Exception.idl"

module InforGuard
{
	interface NetWaterMark
	{
		void Check() raises( ExceptionError );

		long Set(
			inout netCallData callData, 
			in string file,
			in string wm
			) raises( ExceptionError );

		long Get(
			inout netCallData callData, 
			in string file,
			out string wm
			) raises( ExceptionError );
		
		long Add(
			inout netCallData callData, 
			in string filePath
			) raises( ExceptionError );

		long Remove(
			inout netCallData callData, 
			in string filePath
			) raises( ExceptionError );

		long Rename(
			inout netCallData callData, 
			in string oldfilename,
			in string newfilename
			) raises( ExceptionError );

		long Verify(
			inout netCallData callData, 
			in string sFileName, 
			in long nFileSize, 
			in string sWm, 
			in boolean bSimpleSync
			) raises( ExceptionError );

		long VerifyForFilter(
			in string files
			) raises( ExceptionError );
		
		long RequestResume(
			in string filename
			) raises( ExceptionError );
	};
};
