// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MsgTran.proto
#ifndef GRPC_MsgTran_2eproto__INCLUDED
#define GRPC_MsgTran_2eproto__INCLUDED

#include "MsgTran.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace InforGuard_ {

class MsgTran final {
 public:
  static constexpr char const* service_full_name() {
    return "InforGuard_.MsgTran";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq& request, ::InforGuard_::GetMsgRes* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::GetMsgRes>> AsyncGetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::GetMsgRes>>(AsyncGetMsgRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::GetMsgRes>> PrepareAsyncGetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::GetMsgRes>>(PrepareAsyncGetMsgRaw(context, request, cq));
    }
    virtual ::grpc::Status PutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq& request, ::InforGuard_::PutMsgRes* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::PutMsgRes>> AsyncPutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::PutMsgRes>>(AsyncPutMsgRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::PutMsgRes>> PrepareAsyncPutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::PutMsgRes>>(PrepareAsyncPutMsgRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq* request, ::InforGuard_::GetMsgRes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::GetMsgRes* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq* request, ::InforGuard_::GetMsgRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq* request, ::InforGuard_::GetMsgRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::GetMsgRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::GetMsgRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void PutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq* request, ::InforGuard_::PutMsgRes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PutMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::PutMsgRes* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq* request, ::InforGuard_::PutMsgRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq* request, ::InforGuard_::PutMsgRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PutMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::PutMsgRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PutMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::PutMsgRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::GetMsgRes>* AsyncGetMsgRaw(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::GetMsgRes>* PrepareAsyncGetMsgRaw(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::PutMsgRes>* AsyncPutMsgRaw(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InforGuard_::PutMsgRes>* PrepareAsyncPutMsgRaw(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq& request, ::InforGuard_::GetMsgRes* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::GetMsgRes>> AsyncGetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::GetMsgRes>>(AsyncGetMsgRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::GetMsgRes>> PrepareAsyncGetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::GetMsgRes>>(PrepareAsyncGetMsgRaw(context, request, cq));
    }
    ::grpc::Status PutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq& request, ::InforGuard_::PutMsgRes* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::PutMsgRes>> AsyncPutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::PutMsgRes>>(AsyncPutMsgRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::PutMsgRes>> PrepareAsyncPutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InforGuard_::PutMsgRes>>(PrepareAsyncPutMsgRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq* request, ::InforGuard_::GetMsgRes* response, std::function<void(::grpc::Status)>) override;
      void GetMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::GetMsgRes* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq* request, ::InforGuard_::GetMsgRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetMsg(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq* request, ::InforGuard_::GetMsgRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::GetMsgRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::GetMsgRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void PutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq* request, ::InforGuard_::PutMsgRes* response, std::function<void(::grpc::Status)>) override;
      void PutMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::PutMsgRes* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq* request, ::InforGuard_::PutMsgRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PutMsg(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq* request, ::InforGuard_::PutMsgRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PutMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::PutMsgRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PutMsg(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InforGuard_::PutMsgRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::InforGuard_::GetMsgRes>* AsyncGetMsgRaw(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InforGuard_::GetMsgRes>* PrepareAsyncGetMsgRaw(::grpc::ClientContext* context, const ::InforGuard_::GetMsgReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InforGuard_::PutMsgRes>* AsyncPutMsgRaw(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InforGuard_::PutMsgRes>* PrepareAsyncPutMsgRaw(::grpc::ClientContext* context, const ::InforGuard_::PutMsgReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetMsg_;
    const ::grpc::internal::RpcMethod rpcmethod_PutMsg_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetMsg(::grpc::ServerContext* context, const ::InforGuard_::GetMsgReq* request, ::InforGuard_::GetMsgRes* response);
    virtual ::grpc::Status PutMsg(::grpc::ServerContext* context, const ::InforGuard_::PutMsgReq* request, ::InforGuard_::PutMsgRes* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMsg() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::GetMsgReq* /*request*/, ::InforGuard_::GetMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMsg(::grpc::ServerContext* context, ::InforGuard_::GetMsgReq* request, ::grpc::ServerAsyncResponseWriter< ::InforGuard_::GetMsgRes>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PutMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PutMsg() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PutMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::PutMsgReq* /*request*/, ::InforGuard_::PutMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutMsg(::grpc::ServerContext* context, ::InforGuard_::PutMsgReq* request, ::grpc::ServerAsyncResponseWriter< ::InforGuard_::PutMsgRes>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetMsg<WithAsyncMethod_PutMsg<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetMsg() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::InforGuard_::GetMsgReq, ::InforGuard_::GetMsgRes>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::InforGuard_::GetMsgReq* request, ::InforGuard_::GetMsgRes* response) { return this->GetMsg(context, request, response); }));}
    void SetMessageAllocatorFor_GetMsg(
        ::grpc::experimental::MessageAllocator< ::InforGuard_::GetMsgReq, ::InforGuard_::GetMsgRes>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::InforGuard_::GetMsgReq, ::InforGuard_::GetMsgRes>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::GetMsgReq* /*request*/, ::InforGuard_::GetMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetMsg(
      ::grpc::CallbackServerContext* /*context*/, const ::InforGuard_::GetMsgReq* /*request*/, ::InforGuard_::GetMsgRes* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetMsg(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::InforGuard_::GetMsgReq* /*request*/, ::InforGuard_::GetMsgRes* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PutMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PutMsg() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::InforGuard_::PutMsgReq, ::InforGuard_::PutMsgRes>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::InforGuard_::PutMsgReq* request, ::InforGuard_::PutMsgRes* response) { return this->PutMsg(context, request, response); }));}
    void SetMessageAllocatorFor_PutMsg(
        ::grpc::experimental::MessageAllocator< ::InforGuard_::PutMsgReq, ::InforGuard_::PutMsgRes>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::InforGuard_::PutMsgReq, ::InforGuard_::PutMsgRes>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_PutMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::PutMsgReq* /*request*/, ::InforGuard_::PutMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PutMsg(
      ::grpc::CallbackServerContext* /*context*/, const ::InforGuard_::PutMsgReq* /*request*/, ::InforGuard_::PutMsgRes* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PutMsg(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::InforGuard_::PutMsgReq* /*request*/, ::InforGuard_::PutMsgRes* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetMsg<ExperimentalWithCallbackMethod_PutMsg<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetMsg<ExperimentalWithCallbackMethod_PutMsg<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMsg() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::GetMsgReq* /*request*/, ::InforGuard_::GetMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PutMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PutMsg() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PutMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::PutMsgReq* /*request*/, ::InforGuard_::PutMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMsg() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::GetMsgReq* /*request*/, ::InforGuard_::GetMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMsg(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PutMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PutMsg() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PutMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::PutMsgReq* /*request*/, ::InforGuard_::PutMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutMsg(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetMsg() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMsg(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::GetMsgReq* /*request*/, ::InforGuard_::GetMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetMsg(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetMsg(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PutMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PutMsg() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PutMsg(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_PutMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::PutMsgReq* /*request*/, ::InforGuard_::PutMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PutMsg(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PutMsg(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMsg() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InforGuard_::GetMsgReq, ::InforGuard_::GetMsgRes>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::InforGuard_::GetMsgReq, ::InforGuard_::GetMsgRes>* streamer) {
                       return this->StreamedGetMsg(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::GetMsgReq* /*request*/, ::InforGuard_::GetMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMsg(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InforGuard_::GetMsgReq,::InforGuard_::GetMsgRes>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PutMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PutMsg() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InforGuard_::PutMsgReq, ::InforGuard_::PutMsgRes>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::InforGuard_::PutMsgReq, ::InforGuard_::PutMsgRes>* streamer) {
                       return this->StreamedPutMsg(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PutMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PutMsg(::grpc::ServerContext* /*context*/, const ::InforGuard_::PutMsgReq* /*request*/, ::InforGuard_::PutMsgRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPutMsg(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InforGuard_::PutMsgReq,::InforGuard_::PutMsgRes>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetMsg<WithStreamedUnaryMethod_PutMsg<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetMsg<WithStreamedUnaryMethod_PutMsg<Service > > StreamedService;
};

}  // namespace InforGuard_


#endif  // GRPC_MsgTran_2eproto__INCLUDED
